### ISSUE TITLE
[要望] 矢印・フリーズアローのCSSモーション対応

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#352]
**Is your feature request related to a problem? Please describe.
（要望や問題点について記述して下さい）**
- 矢印・フリーズアローにCSSモーションを付加できるようにする。
矢印本体を使用した演出への利用を目的に。

**Describe the solution you'd like
（要望や問題点の解決方法を記述してください）**
- `color_data`と同じような仕様でCSSモーション制御ができるようにする。
```
|motion_data=
300,20,motioncss
400,21,motioncss
|
```

- 仕組みとしては、`makeArrow`や`makeFrzArrow`関数起動時（矢印生成時）に対して
以下のスタイルを適用することで実現する。
`animation-duration`属性にステップゾーン到達フレーム数を適用することで、
速度が変化してもモーションが完了するようにする。
※この方法でモーションが適用できることは確認済み。
```javascript
	stepRoot.classList.add(`toRight`);
	stepRoot.style.animationDuration = `${g_workObj.arrivalFrame[g_scoreObj.frameNum] / 60}s`;
```
```css
.toRight {
	animation-name: leftToRight;
}

@keyframes leftToRight {
	0% {
		opacity: 0;/* 透明 */
		transform: translateX(-50px);
	}
	100% {
		opacity: 1;/* 不透明 */
		transform: translateX(0);
	}
}
```

**Describe alternatives you've considered
（上記の方法ができない場合、他の解決方法案があれば記述してください）**
- 上記方法の場合、速度が上がるたびにモーション時間が短縮されるため、
到達フレーム数に合わせ、モーションの途中から再生する方法が考えられる。
（その代わり、この方法の場合はモーション表示対象が少なくなる懸念がある）

**Additional context
（その他、お気づきの点がありましたらご記入をお願いします）**
